name: 24-7 Music Stream
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Files from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Download Image
          curl -L -H "Authorization: Bearer $HF_TOKEN" \
          "https://huggingface.co/datasets/MASHOLA/YOUTUBE/resolve/main/IMAGES/WASAFI%20MUSIC%20RADIO.png" \
          -o video_bg.png
          
          # Download Audio
          curl -L -H "Authorization: Bearer $HF_TOKEN" \
          "https://huggingface.co/datasets/MASHOLA/YOUTUBE/resolve/main/MUSIC/WASAFI%20MUSIC%20RADIO.wav" \
          -o audio_track.wav

      - name: Start Stream
        run: python stream.py
